package model;
// default package
// Generated 29 mars 2015 16:42:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Joueur generated by hbm2java
 */
public class Joueur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5341147988567063022L;
	private String idjoueur;
	private String motdepasse;
	private Set<Partie> parties = new HashSet<Partie>(0);

	public Joueur() {
	}

	public Joueur(String idjoueur) {
		this.idjoueur = idjoueur;
	}

	public Joueur(String idjoueur, String motdepasse, Set<Partie> parties) {
		this.idjoueur = idjoueur;
		this.motdepasse = motdepasse;
		this.parties = parties;
	}

	public String getIdjoueur() {
		return this.idjoueur;
	}

	public void setIdjoueur(String idjoueur) {
		this.idjoueur = idjoueur;
	}

	public String getMotdepasse() {
		return this.motdepasse;
	}

	public void setMotdepasse(String motdepasse) {
		this.motdepasse = motdepasse;
	}

	public Set<Partie> getParties() {
		return this.parties;
	}

	public void setParties(Set<Partie> parties) {
		this.parties = parties;
	}

}
