package model;
// default package
// Generated 29 mars 2015 16:42:24 by Hibernate Tools 3.4.0.CR1

/**
 * Jouer generated by hbm2java
 */
public class Jouer implements java.io.Serializable {

	private JouerId id;
	private Joueur joueur;
	private Partie partie;
	private String etat;

	public Jouer() {
	}

	public Jouer(JouerId id, Joueur joueur, Partie partie) {
		this.id = id;
		this.joueur = joueur;
		this.partie = partie;
	}

	public Jouer(JouerId id, Joueur joueur, Partie partie, String etat) {
		this.id = id;
		this.joueur = joueur;
		this.partie = partie;
		this.etat = etat;
	}

	public JouerId getId() {
		return this.id;
	}

	public void setId(JouerId id) {
		this.id = id;
	}

	public Joueur getJoueur() {
		return this.joueur;
	}

	public void setJoueur(Joueur joueur) {
		this.joueur = joueur;
	}

	public Partie getPartie() {
		return this.partie;
	}

	public void setPartie(Partie partie) {
		this.partie = partie;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

}
