package model;
// default package
// Generated 29 mars 2015 16:42:24 by Hibernate Tools 3.4.0.CR1

/**
 * JouerId generated by hbm2java
 */
public class JouerId implements java.io.Serializable {

	private String idjoueur;
	private int idpartie;

	public JouerId() {
	}

	public JouerId(String idjoueur, int idpartie) {
		this.idjoueur = idjoueur;
		this.idpartie = idpartie;
	}

	public String getIdjoueur() {
		return this.idjoueur;
	}

	public void setIdjoueur(String idjoueur) {
		this.idjoueur = idjoueur;
	}

	public int getIdpartie() {
		return this.idpartie;
	}

	public void setIdpartie(int idpartie) {
		this.idpartie = idpartie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JouerId))
			return false;
		JouerId castOther = (JouerId) other;

		return ((this.getIdjoueur() == castOther.getIdjoueur()) || (this
				.getIdjoueur() != null && castOther.getIdjoueur() != null && this
				.getIdjoueur().equals(castOther.getIdjoueur())))
				&& (this.getIdpartie() == castOther.getIdpartie());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdjoueur() == null ? 0 : this.getIdjoueur().hashCode());
		result = 37 * result + this.getIdpartie();
		return result;
	}

}
